'use strict';

import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';

// Import Selectors
import { getUser } from '../UserReducer';

// Material
import Toggle from 'material-ui/Toggle';
import Dialog from 'material-ui/Dialog';
import FlatButton from 'material-ui/FlatButton';

const styles = {
  wizardStepPageStyle: {
    maxHeight: 350,
    minWidth:317
    // maxWidth: 679,
    // overflow:'auto',
  },
  termsSection:{
    maxHeight: 383,
    overflow:'auto',
    display:'inline-flex',
    width:'100%',
    flexDirection:'column'
  },
  toggle: {
    // marginBottom: 15,
    marginTop: 15,
    maxWidth:250,
    display:'inline-flex',
    width:'100%'
  }
};

class StepNumber3 extends Component {
  constructor(props) {
    super(props);

    this.state = {
      dialogOpen : false
    };

    //Binds
    this.stateChanged = this.stateChanged.bind(this);
    this.handleOpen = this.handleOpen.bind(this);
    this.handleClose = this.handleClose.bind(this);
    this.isValidated = this.isValidated.bind(this);
  }

  componentDidMount() {
    this.context.mixpanel.track('Wizard step open',{'ab_version':'v1','step':'3'});
  }

  isValidated() {
    console.log(this.state);
    if(!this.props.user.agreed_terms){
      this.handleOpen();
    }
    return this.props.user.agreed_terms;
  }

  stateChanged(value,isInputChecked){
    this.props.user.agreed_terms = isInputChecked;
    this.setState({user: this.props.user});
    console.log(this.state);
  }

  handleOpen = () => {
    this.setState({dialogOpen: true});
  };

  handleClose = () => {
    this.setState({dialogOpen: false});
  };

  render() {
    const actions = [
      <FlatButton
        label="Ok"
        primary={true}
        keyboardFocused={true}
        onTouchTap={this.handleClose}
      />,
    ];

    return (
      <div className="step step2" style={styles.wizardStepPageStyle}>
        <section style={styles.termsSection} >
          <h2>Terms of Use</h2>
          <div className="col-md-12">
            <p>Last Updated Date: August 30th, 2016</p>
            <p>PLEASE READ THIS TERMS OF USE AGREEMENT (THE <b>&ldquo;TERMS&rdquo;</b>) CAREFULLY. BY ACCESSING OR USING THIS WEBSITE OR ANY OTHER WEBSITES OF INSTRUCTURE, INC. (<b>&ldquo;INSTRUCTURE&rdquo;</b>) WITH LINKS TO THIS AGREEMENT (COLLECTIVELY, THE <b>&ldquo;WEBSITE&rdquo;</b>) IN ANY WAY, INCLUDING USING THE SERVICES ENABLED VIA THE WEBSITE (THE <b>&ldquo;SERVICES&rdquo;</b>) BY INSTRUCTURE OR USERS OF THE SITE (<b>&ldquo;USERS&rdquo;</b>), CLICKING THE &ldquo;I ACCEPT&rdquo; CHECK BOX, OR MERELY BROWSING THE WEBSITE, YOU REPRESENT THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THE TERMS.  <b>IF YOU DO NOT AGREE TO BE BOUND BY THE TERMS, YOU MAY NOT ACCESS OR USE THIS WEBSITE OR THE SERVICES.</b> </p>
            <p>THESE TERMS INCLUDE A CLASS ACTION WAIVER AND WAIVER OF JURY TRIALS, AND REQUIRE BINDING ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE DISPUTES.</p>
            <p>The Services include, but are not limited to, a learning management system that entities (<b>&ldquo;Entities&rdquo;</b>) may subscribe to and provide to their instructors and learners (<b>&ldquo;Instructors&rdquo;</b> and <b>&ldquo;Learners&rdquo;</b>) in connection with courses (each, a <b>&ldquo;Course&rdquo;</b>). Instructure provides an account that enables a designated User to manage the Services, manage Learner and Instructor access to the Services, and provide general support on behalf of an Entity. &ldquo;User&rdquo; means any user of the Services, including Learners, and Instructors. </p>
            <p>PLEASE NOTE THAT THE TERMS ARE SUBJECT TO CHANGE BY INSTRUCTURE IN ITS SOLE DISCRETION AT ANY TIME.  When changes are made, Instructure will make a new copy of the Terms available at the Website.  We will also update the &ldquo;Last Updated&rdquo; date at the top of the Terms.  If we make any material changes, and you have registered to use the Services, we will also send an e-mail to you at the last e-mail address you provided to us.  Any changes to the Terms will be effective immediately for new Users of the Website or Services and will be effective thirty (30) days after posting of notice of such changes on the Website for existing User.  Instructure may require you to provide consent to the updated Terms in a specified manner before further use of the Website or the Services is permitted.  If you do not agree to any change(s) after receiving a notice of such change(s), you shall stop using the Website and/or the Services.  Otherwise, your continued use of the Website and/or the Services constitutes your acceptance of such change(s).  PLEASE REGULARLY CHECK THE WEBSITE TO VIEW THE THEN-CURRENT TERMS. </p>
            <p><b>1.	Use of the Services and Instructure Properties.</b>  The Website, the Services, and the information and content made available (<b>&ldquo;Content&rdquo;</b>) by Instructure on the Website and in the Services (collectively, the <b>&ldquo;Instructure Properties&rdquo;</b>) are protected by copyright laws throughout the world.  Subject to the Terms, Instructure grants you a limited license to reproduce portions of the Instructure Properties for the sole purpose of using the Services for your personal purposes or, in the event you are an Instructor, your educational purposes. </p>
            <p><b>1.1	Application License.</b>  Instructure also provides a mobile application (the <b>&ldquo;Application&rdquo;</b>) for use with the Services. Your use of the Application is governed by the End User License Agreement that accompanies the Application in the marketplace where you download it. </p>
            <p><b>1.2	Certain Restrictions.</b>  The rights granted to you in the Terms are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, reproduce, distribute, host or otherwise commercially exploit the Instructure Properties, (b) you shall not use framing techniques to enclose any trademark, logo, or other Instructure Properties; (c) you shall not use any metatags or other &ldquo;hidden text&rdquo; using Instructure’s name or trademarks; (d) you shall not modify, translate, adapt, merge, make derivative works of, disassemble, decompile, reverse compile or reverse engineer any part of the Instructure Properties except to the extent the foregoing restrictions are expressly prohibited by applicable law; (e) you shall not use any manual or automated software, devices, or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools, or the like) to &ldquo;scrape&rdquo; or download data from any web pages contained in the Website; (f) except as expressly stated herein, no part of the Instructure Properties may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means; and (g) you shall not remove or destroy any copyright notices or other proprietary markings contained on or in the Instructure Properties. Any future release, update or other addition to the Instructure Properties shall be subject to the Terms.  Instructure, its suppliers and service providers reserve all rights not granted in the Terms.  Any unauthorized use of the Instructure Properties terminates the licenses granted by Instructure pursuant to the Terms. </p>
            <p><b>2.	Registration.</b> In order to access certain features of the Instructure Properties you must create an account (<b>&ldquo;Account&rdquo;</b>).  Certain features are only available to Instructor Accounts.</p>
            <p><b>2.1	Instructor Accounts.</b>  If you an Instructor, Instructure will provide you with access to an Instructor Account, provided that you (1) provide any necessary information about you and/or your school when registering the Account (<b>&ldquo;Registration Data&rdquo;</b>) and (2) accept the Terms. Using your Instructor Account, you may create invitations for Learner Accounts by generating invite codes that you may provide to your Students.  You will be responsible for any activities, including any violation of the Terms that occur under Student Accounts created using your Instructor Account.  </p>
            <p><b>2.2	Learner Accounts.</b> To create a Learner Account, you must (1) be provided with access to an account invite code by an Instructor, (2) provide us with any Registration Data requested in the registration form, and (3) accept the Terms.</p>
            <p><b>2.3	Registration Data.</b>  In registering for the Services, you agree to (1) provide true, current, and complete Registration Data; and (2) maintain and promptly update the Registration Data to keep it true, current, and complete. You are responsible for all activities that occur under your Account. You may not share your Account or password with anyone, and you agree to notify Instructure immediately of any unauthorized use of your password or any other breach of security.  You agree not to create or access an Account using a false identity or information, or on behalf of someone other than yourself.  You agree that you shall not have more than one Account at any given time.  You agree not to create an Account or use the Instructure Properties if you have been previously removed by Instructure, or if you have been previously banned from any of the Instructure Properties.</p>
            <p><b>2.4	Social Networking Services.</b> We may permit you to login to the Services with your login credentials from certain social networking sites (e.g., Facebook) (<b>&ldquo;SNS&rdquo;</b>). If you log in or otherwise associate your Account with your login credentials from such SNS, we may receive information about you from such SNS, in accordance with the terms and conditions (e.g., terms of use and privacy policy) of the SNS (<b>&ldquo;SNS Terms&rdquo;</b>). If you elect to share your information with these SNS, we will share information with them in accordance with your election. The SNS Terms of such SNS will apply to the information we disclose to them.</p>
            <p><b>2.5	Necessary Equipment and Software.</b>  You must provide all equipment and software necessary to connect to the Instructure Properties, including but not limited to, a mobile device that is suitable to connect with and use the Application.  You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Instructure Properties.</p>
            <p><b>3.	Payment Terms.</b> Some of the Courses offered as part of the Services are available to Learners in exchange for a fee. You may purchase such Courses by following the directions on the Site.  If you purchase a Course, you agree to pay the then-current applicable Course fee listed on the Site (<b>&ldquo;Course Fees&rdquo;</b>) and Instructure will bill the credit card or PayPal account you submit in purchasing the Course.  All payments are refundable according to Instructure’s standard refund policy or the refund policy posted on the applicable Course enrollment page, if any.  In the event of a conflict between Instructure’s standard refund policy and the refund policy posted on a Course enrollment page, the Course enrollment page will control. You hereby authorize Instructure to bill your credit card or PayPal account, as applicable, for the Course Fees as described above.  Course Fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and you are responsible for payment of all such taxes, levies or duties. If any Course Fee cannot be charged to your credit card or PayPal account for any reason, Instructure may provide you, via email, notice of such non-payment and a link for you to update your payment information.  If such non-payment is not remedied within seven (7) days after receiving such notice of non-payment, Instructure may terminate your access to the applicable Course</p>
            <p><b>4.	Responsibility for Content.</b></p>
            <p><b>4.1	Types of Content.</b>  You acknowledge that all Content, including the Instructure Properties, is the sole responsibility of the party from whom such Content originated.  This means that you, and not Instructure, are entirely responsible for all Content that you upload, post, e-mail, transmit or otherwise make available (<b>&ldquo;Make Available&rdquo;</b>) through the Instructure Properties (<b>&ldquo;Your Content&rdquo;</b>).  Other Users of the Instructure Properties, and not Instructure, are similarly responsible for all Content such other Users Make Available through the Instructure Properties (<b>&ldquo;User Content&rdquo;</b>).</p>
            <p><b>4.2	No Obligation to Pre-Screen Content.</b>  You acknowledge that Instructure has no obligation to pre-screen Content (including, but not limited to, Your Content and User Content), although Instructure reserves the right in its sole discretion to pre-screen, refuse, or remove any Content that (1) violates any law or regulation, (2) violates these Terms, including the User Code of Conduct set forth in Section 5.4 hereof, and/or (3) otherwise creates liability for Instructure.</p>
            <p><b>5.	Ownership.</b></p>
            <p><b>5.1	Instructure Properties.</b>  Except with respect to Your Content and User Content, you agree that Instructure and its suppliers own all rights, title and interest in the Instructure Properties.  Instructure’s name and other related graphics, logos, service marks and trade names used on or in connection with the Instructure Properties are the trademarks of Instructure and may not be used without permission in connection with any third-party products or services.  Other trademarks, service marks and trade names that may appear on or in the Instructure Properties are the property of their respective owners.</p>
            <p><b>5.2	Your Content.</b> Your Content shall at all times remain your sole property and you agree that you have no right, title or interest in or to any other Content that appears on or in the Instructure Properties. You represent that you have all necessary right, power and authority to post Your Content to the Instructure Properties. You agree to allow Instructure and its applicable contractors to freely host, reproduce, transmit, modify, display and otherwise use Your Content (in whole or in part) as reasonably necessary to provide the Services to you, and in accordance with Instructure’s agreement with your Entity, if applicable.</p>
            <p><b>5.3	Your Account.</b>  Notwithstanding anything contained herein to the contrary, by submitting Your Content to any forums, comments or any other area on or in the Instructure Properties, you hereby expressly permit Instructure to identify you by your username as the contributor of Your Content in any publication in any form, media, or technology now known or later developed in connection with Your Content. </p>
            <p><b>5.4	User Code of Conduct.</b>  As a condition of use, you agree not to use the Instructure Properties for any purpose that is prohibited by the Terms or by applicable law. Do not post, or permit others to post, content on the Instructure Properties or on your profile that (i) encourages illegal activities, is fraudulent, or is unlawful; (ii) insults, defames, harasses, or threatens others; (iii) violates the copyright or intellectual property or privacy rights of others; (iv) contains obscene, vulgar, pornographic, or libelous material; (v) harms or impersonates others, including other Users; or (vi) advertises or sells a product or service. Do not reproduce content from your Course or other Learners unless allowed by the express copyright terms laid out by the Instructor (e.g. Creative Commons). Do not share the solutions to assignments with others unless this is expressly authorized by the Instructor. Do not submit the work of others as your own work. Respect the privacy of other Users. Respect the diversity of opinions and cultures that will be presented by other Users. Do not attempt or engage in, any potentially harmful acts that are directed against the Instructure Properties, including but not limited to violating or attempting to violate any security features of the Instructure Properties, introducing viruses, worms, or similar harmful code into the Instructure Properties, or interfering or attempting to interfere with use of the Instructure Properties by any other user, host or network, including by means of overloading, &ldquo;flooding,&rdquo; &ldquo;spamming,&rdquo; &ldquo;mail bombing,&rdquo; or &ldquo;crashing&rdquo; the Instructure Properties.  If you believe that someone has violated this code of conduct, begin by notifying the Instructor of the Course. If the issue is not addressed by the Instructor to your satisfaction, contact <a href="mailto:conduct@canvas.net" target="_blank">conduct@canvas.net</a> with your concerns.</p>
            <p><b>5.5	Feedback.</b>  You agree that submission of any ideas, suggestions, documents, and/or proposals to Instructure through its suggestion, feedback, wiki, forum or similar pages (<b>&ldquo;Feedback&rdquo;</b>) is at your own risk and that Instructure has no obligations (including without limitation obligations of confidentiality) with respect to such Feedback.  You represent and warrant that you have all rights necessary to submit the Feedback.  You hereby grant to Instructure a fully paid, royalty-free, perpetual, irrevocable, worldwide, non-exclusive, and fully sublicensable right and license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all Feedback, and to sublicense the foregoing rights, in connection with the operation and maintenance of the Instructure Properties.</p>
            <p><b>6.	Investigations.</b>  Instructure may, but is not obligated to, monitor or review the Instructure Properties and Content at any time.  Without limiting the foregoing, Instructure shall have the right, in its sole discretion, to remove any of Your Content for any reason (or no reason), including if such Content violates the Terms or any applicable law.  Although Instructure does not generally monitor user activity occurring in connection with the Instructure Properties, if Instructure becomes aware of any possible violations by you of any provision of the Terms, Instructure reserves the right to investigate such violations, and Instructure may, at its sole discretion, terminate your license to use the Instructure Properties, or change, alter or remove Your Content, in whole or in part.</p>
            <p><b>7.	Interactions with Other Users.</b></p>
            <p><b>7.1	User Responsibility.</b>  You are solely responsible for your interactions with other Users of the Services and any other parties with whom you interact through the Services; provided, however, that Instructure reserves the right, but has no obligation, to intercede in disputes among Users.  You agree that Instructure will not be responsible for any liabilities incurred as the result of such interaction.</p>
            <p><b>7.2	Content Provided by Other Users.</b>  The Instructure Properties may contain User Content provided by other Users.  Instructure is not responsible for and does not control User Content.  Instructure has no obligation to review or monitor, and does not approve, endorse or make any representations or warranties with respect to User Content.  You use all User Content and interact with other Users at your own risk.</p>
            <p><b>8.	Third-Party Websites.</b></p>
            <p><b>8.1	Third-Party Websites.</b>  The Instructure Properties may contain links to third-party websites (<b>&ldquo;Third-Party Websites&rdquo;</b>).  When you click on a link to a Third-Party Website, we will not warn you that you have left the Instructure Properties and are subject to separate terms and conditions or privacy policies.  Such Third-Party Websites are not under the control of Instructure.  Instructure is not responsible for any Third-Party Websites and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites, or their products or services.  You use all links in Third-Party Websites at your own risk. You should review applicable terms and policies, including privacy and data gathering practices, of any Third-Party Websites, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third-party. </p>
            <p><b>8.2	App Stores.</b>  You acknowledge and agree that the availability of the Application and the Services is dependent on the third-party from which you received the Application, e.g., the Apple or Android app stores.  </p>
            <p><b>9.	Indemnification.</b> You agree to indemnify, defend, and hold Instructure, its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (collectively the <b>&ldquo;Instructure Parties&rdquo;</b>) harmless from any losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of: (a) Your Content; (b) your use of, or inability to use, the Instructure Properties; (c) your violation of the Terms; (d) your violation of any rights of another party, including any User; or (e) your violation of any applicable laws, rules or regulations.  Instructure reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Instructure in asserting any available defenses.  You agree that the provisions in this section will survive any termination of your Account, the Terms, or your access to the Instructure Properties. </p>
            <p><b>10.	Disclaimer of Warranties.</b> YOU EXPRESSLY UNDERSTAND AND AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOUR USE OF THE INSTRUCTURE PROPERTIES IS AT YOUR SOLE RISK, AND THE INSTRUCTURE PROPERTIES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITH ALL FAULTS.  INSTRUCTURE PARTIES EXPRESSLY DISCLAIM ALL WARRANTIES, REPRESENTATIONS, AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. INSTRUCTURE PARTIES MAKE NO WARRANTY, REPRESENTATION OR CONDITION THAT: (1) THE INSTRUCTURE PROPERTIES WILL MEET YOUR REQUIREMENTS; (2) YOUR USE OF THE INSTRUCTURE PROPERTIES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (3) THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE INSTRUCTURE PROPERTIES WILL BE ACCURATE OR RELIABLE; OR (4) ANY ERRORS IN THE INSTRUCTURE PROPERTIES WILL BE CORRECTED. ANY CONTENT DOWNLOADED FROM OR OTHERWISE ACCESSED THROUGH THE INSTRUCTURE PROPERTIES IS ACCESSED AT YOUR OWN RISK, AND YOU SHALL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR PROPERTY OR PERSON, INCLUDING, BUT NOT LIMITED TO, YOUR COMPUTER SYSTEM AND ANY DEVICE YOU USE TO ACCESS THE INSTRUCTURE PROPERTIES, OR ANY OTHER LOSS THAT RESULTS FROM ACCESSING SUCH CONTENT. THE SERVICES MAY BE SUBJECT TO DELAYS, CANCELLATIONS AND OTHER DISRUPTIONS.  INSTRUCTURE MAKES NO WARRANTY, REPRESENTATION OR CONDITION WITH RESPECT TO THE SERVICES, INCLUDING BUT NOT LIMITED TO, THE QUALITY, EFFECTIVENESS, REPUTATION AND OTHER CHARACTERISTICS OF THE SERVICES. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM INSTRUCTURE OR THROUGH THE INSTRUCTURE PROPERTIES WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN. </p>
            <p><b>11.	Limitation of Liability.</b></p>
            <p><b>11.1	Disclaimer of Certain Damages.</b>  YOU UNDERSTAND AND AGREE THAT IN NO EVENT SHALL INSTRUCTURE PARTIES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE INSTRUCTURE PROPERTIES, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROFITS, WHETHER OR NOT INSTRUCTURE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH THE TERMS, OR FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER USERS OF THE INSTRUCTURE PROPERTIES, ON ANY THEORY OF LIABILITY, RESULTING FROM: (1) THE USE OR INABILITY TO USE THE INSTRUCTURE PROPERTIES; (2) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED FOR TRANSACTIONS ENTERED INTO THROUGH THE INSTRUCTURE PROPERTIES; (3) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (4) STATEMENTS OR CONDUCT OF ANY THIRD-PARTY ON INSTRUCTURE PROPERTIES; OR (5) ANY OTHER MATTER RELATED TO THE INSTRUCTURE PROPERTIES, WHETHER BASED ON WARRANTY, COPYRIGHT, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY.</p>
            <p><b>11.2	Cap on Liability.</b>  UNDER NO CIRCUMSTANCES WILL INSTRUCTURE PARTIES BE LIABLE TO YOU FOR MORE THAN FIFTY DOLLARS ($50). </p>
            <p><b>11.3	User Content.</b>  INSTRUCTURE PARTIES ASSUME NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, MIS-DELIVERY OR FAILURE TO STORE ANY CONTENT (INCLUDING, BUT NOT LIMITED TO, YOUR CONTENT AND USER CONTENT), USER COMMUNICATIONS OR PERSONALIZATION SETTINGS.</p>
            <p><b>11.4	No Liability for Conduct of Third Parties or Other Users.</b>  YOU ACKNOWLEDGE AND AGREE THAT INSTRUCTURE PARTIES ARE NOT LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD INSTRUCTURE PARTIES LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OPERATORS OF EXTERNAL SITES, AND THAT THE RISK OF INJURY FROM SUCH THIRD PARTIES RESTS ENTIRELY WITH YOU. YOU ARE SOLELY RESPONSIBLE FOR ALL OF YOUR COMMUNICATIONS AND INTERACTIONS WITH OTHER USERS OF THE INSTRUCTURE PROPERTIES. YOU UNDERSTAND THAT INSTRUCTURE DOES NOT MAKE ANY ATTEMPT TO VERIFY THE STATEMENTS OF USERS OF THE INSTRUCTURE PROPERTIES. </p>
            <p><b>11.5	Basis of the Bargain.</b>  THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN INSTRUCTURE AND YOU. </p>
            <p><b>12.	Procedure for Making Claims of Copyright Infringement.</b>  It is Instructure’s policy to terminate membership privileges of any User who repeatedly infringes copyright upon prompt notification to Instructure by the copyright owner or the copyright owner’s legal agent.  Without limiting the foregoing, if you believe that your work has been copied and posted on the Instructure Properties in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: (1) an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; (2) a description of the copyrighted work that you claim has been infringed; (3) a description of the location on the Instructure Properties of the material that you claim is infringing; (4) your address, telephone number and e-mail address; (5) a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (6) a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.  Contact information for Instructure’s Copyright Agent for notice of claims of copyright infringement is as follows: Howard Baik; 6330 South 3000 East, Suite 700, Salt Lake City, UT 84121; <a href="mailto:legal@instructure.com" target="_blank">legal@instructure.com</a>.</p>
            <p><b>13.	Term and Termination.</b></p>
            <p><b>13.1	Term.</b>  The Terms commence on the date when you accept them (as described in the preamble above) and remain in full force and effect while you use the Instructure Properties, unless terminated earlier in accordance with the Terms.</p>
            <p><b>13.2	Termination of Services by Instructure.</b>  If you have breached any provision of the Terms, or if Instructure is required to do so by law (e.g., where the provision of the Website, the Application, or the Services is, or becomes, unlawful), Instructure has the right to suspend or terminate any Services provided to you or to delete any of Your Content. You agree that all terminations for cause shall be made in Instructure’s sole discretion and that Instructure shall not be liable to you or any third-party for any termination of your Account. Termination of any Service includes removal of access to such Service and barring of further use of the Service.  Termination of  all Services also may include deletion of your password and all related information, files and Content associated with or inside your Account (or any part thereof), including Your Content.  Upon termination of any Service, your right to use such Service will automatically terminate immediately.  Instructure will not have any liability whatsoever to you for any suspension or termination, including for deletion of Your Content.  All provisions of the Terms which by their nature should survive, shall survive termination of Services, including without limitation, ownership provisions, warranty disclaimers, and limitation of liability.</p>
            <p><b>14.	General Provisions.</b></p>
            <p><b>14.1	Electronic Communications.</b>  The communications between you and Instructure use electronic means, whether you visit the Instructure Properties or send Instructure e-mails, or whether Instructure posts notices on the Instructure Properties or communicates with you via e-mail.  For contractual purposes, you (1) consent to receive communications from Instructure in an electronic form; and (2) agree that all terms and conditions, agreements, notices, disclosures, and other communications that Instructure provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be in writing.  The foregoing does not affect any statutory rights you may have.</p>
            <p><b>14.2	Release.</b>  You hereby release Instructure Parties and their successors from claims, demands, any and all losses, damages, rights, and actions of any kind, including personal injuries, death, and property damage, that is either directly or indirectly related to or arises from any interactions with or conduct of other Website Users or third-party websites of any kind arising in connection with or as a result of the Terms or your use of the Instructure Properties.  If you are a California resident, you hereby waive California Civil Code Section 1542, which states, &ldquo;A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.&rdquo;</p>
            <p><b>14.3	Assignment.</b>  The Terms, and your rights and obligations hereunder, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Instructure’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. Instructure may assign its rights and obligations under these Terms to a third party without your consent.</p>
            <p><b>14.4	Force Majeure.</b>  Instructure shall not be liable for any delay or failure to perform resulting from causes outside its reasonable control, including, but not limited to, acts of God, war, terrorism, riots, embargos, acts of civil or military authorities, fire, floods, accidents, strikes or shortages of transportation facilities, fuel, energy, labor or materials.</p>
            <p><b>14.5	Compliance.</b>  If you believe that Instructure has not adhered to the Terms, please contact Instructure by emailing us at <a href="mailto:legal@instructure.com" target="_blank">legal@instructure.com</a>.  We will do our best to address your concerns.  If you feel that your complaint has been addressed incompletely, we invite you to let us know for further investigation.</p>
            <p><b>14.6	Arbitration Agreement; Class Waiver; Waiver of Trial by Jury. </b></p>
            <p>Please read this Arbitration Agreement carefully.  It is part of your contract with Instructure and affects your rights.  It contains procedures for MANDATORY BINDING ARBITRATION AND A CLASS ACTION WAIVER.   </p>
            <p>(a)	Applicability of Arbitration Agreement. All claims and disputes (excluding claims for injunctive or other equitable relief as set forth below) in connection with the Terms or the use of any product or service provided by Instructure that cannot be resolved informally or in small claims court shall be resolved by binding arbitration on an individual basis under the terms of this Arbitration Agreement.  This Arbitration Agreement applies to you and Instructure, and to any subsidiaries, affiliates, agents, employees, predecessors in interest, successors, and assigns, as well as all authorized or unauthorized users or beneficiaries of services or goods provided under the Terms.</p>
            <p>(b)	Notice Requirement and Informal Dispute Resolution.  Before either party may seek arbitration, the party must first send to the other party a written Notice of Dispute (&ldquo;Notice&rdquo;) describing the nature and basis of the claim or dispute, and the requested relief.  A Notice to Instructure should be sent to: Attn: Legal Department, 6330 South 3000 East, Suite 700, Salt Lake City, UT 84121.  After the Notice is received, you and Instructure may attempt to resolve the claim or dispute informally.  If you and Instructure do not resolve the claim or dispute within 30 days after the Notice is received, either party may begin an arbitration proceeding.  The amount of any settlement offer made by any party may not be disclosed to the arbitrator until after the arbitrator has determined the amount of the award, if any, to which either party is entitled.  </p>
            <p>(c)	Arbitration Rules.  Arbitration shall be initiated through the American Arbitration Association (&ldquo;AAA&rdquo;), an established alternative dispute resolution provider (&ldquo;ADR Provider&rdquo;) that offers arbitration as set forth in this section.  If AAA is not available to arbitrate, the parties shall agree to select an alternative ADR Provider.  The rules of the ADR Provider shall govern all aspects of this arbitration, including but not limited to the method of initiating and/or demanding arbitration, except to the extent such rules are in conflict with the Terms. The AAA Consumer Arbitration Rules governing the arbitration are available online at www.adr.org or by calling the AAA at 1-800-778-7879.  The arbitration shall be conducted by a single, neutral arbitrator.  Any claims or disputes where the total amount of the award sought is less than Ten Thousand U.S. Dollars (US $10,000.00) may  be resolved through binding non-appearance-based arbitration, at the option of the party seeking relief.  For claims or disputes where the total amount of the award sought is Ten Thousand U.S. Dollars (US $10,000.00) or more, the right to a hearing will be determined by the Arbitration Rules.  Any hearing will be held in a location within 100 miles of your residence, unless you reside outside of the United States, and unless the parties agree otherwise.  Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Each party shall bear its own costs (including attorney’s fees) and disbursements arising out of the arbitration, and shall pay an equal share of the fees and costs of the ADR Provider.  </p>
            <p>(d)	Additional Rules for Non-appearance Based Arbitration: If non-appearance arbitration is elected, the arbitration shall be conducted by telephone, online and/or based solely on written submissions; the specific manner shall be chosen by the party initiating the arbitration.  The arbitration shall not involve any personal appearance by the parties or witnesses unless otherwise mutually agreed by the parties.</p>
            <p>(e)	Time Limits.  If you or Instructure pursue arbitration, the arbitration action must be initiated and/or demanded within the statute of limitations (i.e., the legal deadline for filing a claim) and within any deadline imposed under the AAA Rules for the pertinent claim.</p>
            <p>(f)	Authority of Arbitrator.  If arbitration is initiated, the arbitrator will decide the rights and liabilities, if any, of you and Instructure, and the dispute will not be consolidated with any other matters or joined with any other cases or parties.  The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non-monetary remedy or relief available to an individual under applicable law, the AAA Rules, and the Terms.  The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded.  The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have.  The award of the arbitrator is final and binding upon you and Instructure.  </p>
            <p>(g)	Waiver of Jury Trial.  THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement.  Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in court and are subject to very limited review by a court.  In the event any litigation should arise between you and Instructure in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND INSTRUCTURE WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge.</p>
            <p>(h)	Waiver of Class or Consolidated Actions.  ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.</p>
            <p>(i)	Confidentiality. All aspects of the arbitration proceeding, including but not limited to the award of the arbitrator and compliance therewith, shall be strictly confidential. The parties agree to maintain confidentiality unless otherwise required by law.  This Paragraph shall not prevent a party from submitting to a court of law any information necessary to enforce this Agreement, to enforce an arbitration award, or to seek injunctive or equitable relief. </p>
            <p>(j)	Severability. If any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable by a court of competent jurisdiction, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Agreement shall continue in full force and effect.</p>
            <p>(k)	Right to Waive.  Any or all of the rights and limitations set forth in this Agreement may be waived by the party against whom the claim is asserted.  Such waiver shall not waive or effect any other portion of this Agreement.</p>
            <p>(l)	Survival of Agreement. This Arbitration Agreement will survive the termination of your relationship with Instructure.</p>
            <p>(m)	Small Claims Court.  Notwithstanding the foregoing, either you or Instructure may bring an individual action in small claims court.</p>
            <p>(n)	Emergency Equitable Relief.  Notwithstanding the foregoing, either party may seek emergency equitable relief before a state or federal court in order to maintain the status quo pending arbitration.  A request for interim measures shall not be deemed a waiver of any other rights or obligations under this Arbitration Agreement.</p>
            <p>(o)	Claims Not Subject To Arbitration.  Notwithstanding the foregoing, claims of defamation, violation of the Computer Fraud and Abuse Act, and infringement or misappropriation of the other party’s patent, copyright, trademark, or trade secret shall not be subject to this arbitration agreement.  </p>
            <p>(p)	Courts.  In any circumstances where the foregoing Agreement permits the parties to litigate in court, the parties hereby agree to submit to the personal jurisdiction of the courts located within Salt Lake County, Utah, for such purpose.    </p>
            <p><b>14.7	Governing Law.</b>  The Terms and any action related thereto will be governed and interpreted by and under the laws of the State of Utah, consistent with the Federal Arbitration Act, without giving effect to any conflicts of law principles that provide for the application of the law of another jurisdiction.  The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.</p>
            <p><b>14.8	Notice.</b>  Where Instructure requires that you provide an e-mail address to access certain features of the Instructure Properties, you are responsible for providing Instructure with your most current e-mail address.  In the event that the last e-mail address you provided to Instructure is not valid, or for any reason is not capable of delivering to you any notices required/ permitted by the Terms, Instructure’s dispatch of the e-mail containing such notice will nonetheless constitute effective notice.  You may give notice to Instructure at the following address:  Attn: Legal Department, 6330 South 3000 East, Suite 700, Salt Lake City, UT 84121.  Such notice shall be deemed given when received by Instructure by letter delivered by nationally recognized overnight delivery service or first class postage prepaid mail at the above address.</p>
            <p><b>14.9	Waiver.</b>  Any waiver or failure by Instructure to enforce any provision of the Terms on one occasion will not be deemed a waiver of any other provision or of such provision on any other occasion.</p>
            <p><b>14.10	Severability.</b>  If any provision of the Terms is, for any reason, held to be invalid or unenforceable, the other provisions of the Terms will remain enforceable, and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law.</p>
            <p><b>14.11	Entire Agreement.</b>  The Terms are the final, complete and exclusive agreement of the parties with respect to the subject matter hereof and supersedes and merges all prior discussions between the parties with respect to such subject matter.</p>
          </div>
        </section>
        <div style={styles.block} className="col-md-12">
          <Toggle
            label="I agree"
            style={styles.toggle}
            onToggle={this.stateChanged}
            toggled={ this.props.user.agreed_terms}
          />
        </div>
        <Dialog
          title="Agree terms"
          actions={actions}
          modal={false}
          open={this.state.dialogOpen}
          onRequestClose={this.handleClose}
        >
          You must agree in order to see your results
        </Dialog>
      </div>
    )
  }
}


function mapStateToProps(state) {
  return {
    user: getUser(state),
  };
}

StepNumber3.propTypes = {
  user: PropTypes.any
};

StepNumber3.contextTypes = {
  mixpanel: PropTypes.any
};

export default connect(mapStateToProps, null, null, { withRef: true })(StepNumber3);
